# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: ReerKit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  Linux:
    runs-on: [ubuntu-latest]
    container: swift:5.10
    steps:
      - uses: actions/checkout@v1
      - name: Linux
        run: swift build -v
